Name:               aks-users-14533555-vmss000006
Roles:              agent
Labels:             agentpool=users
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D8s_v3
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=westeurope
                    failure-domain.beta.kubernetes.io/zone=0
                    hub.jupyter.org/node-purpose=user
                    kubernetes.azure.com/agentpool=users
                    kubernetes.azure.com/cluster=MC_rg-pc-cng_cngcluster_westeurope
                    kubernetes.azure.com/mode=user
                    kubernetes.azure.com/node-image-version=AKSUbuntu-1804gen2containerd-2022.03.29
                    kubernetes.azure.com/os-sku=Ubuntu
                    kubernetes.azure.com/role=agent
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=aks-users-14533555-vmss000006
                    kubernetes.io/os=linux
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    node.kubernetes.io/instance-type=Standard_D8s_v3
                    topology.disk.csi.azure.com/zone=
                    topology.kubernetes.io/region=westeurope
                    topology.kubernetes.io/zone=0
Annotations:        csi.volume.kubernetes.io/nodeid: {"disk.csi.azure.com":"aks-users-14533555-vmss000006","file.csi.azure.com":"aks-users-14533555-vmss000006"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 19 Apr 2022 10:11:02 -0700
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  aks-users-14533555-vmss000006
  AcquireTime:     <unset>
  RenewTime:       Tue, 19 Apr 2022 10:17:51 -0700
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Tue, 19 Apr 2022 10:11:38 -0700   Tue, 19 Apr 2022 10:11:38 -0700   RouteCreated                 RouteController created a route
  MemoryPressure       False   Tue, 19 Apr 2022 10:15:42 -0700   Tue, 19 Apr 2022 10:11:02 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Tue, 19 Apr 2022 10:15:42 -0700   Tue, 19 Apr 2022 10:11:02 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Tue, 19 Apr 2022 10:15:42 -0700   Tue, 19 Apr 2022 10:11:02 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Tue, 19 Apr 2022 10:15:42 -0700   Tue, 19 Apr 2022 10:11:12 -0700   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  Hostname:    aks-users-14533555-vmss000006
  InternalIP:  10.240.0.7
Capacity:
  attachable-volumes-azure-disk:  16
  cpu:                            8
  ephemeral-storage:              129900528Ki
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         32882856Ki
  pods:                           110
Allocatable:
  attachable-volumes-azure-disk:  16
  cpu:                            7820m
  ephemeral-storage:              119716326407
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  memory:                         28382376Ki
  pods:                           110
System Info:
  Machine ID:                 f0491616424f42eab7691122b59729b5
  System UUID:                6b280cc2-54b8-4059-aae0-70bc7c4f68b5
  Boot ID:                    46e1b8b0-6cd2-46b9-b83a-d859ae571d18
  Kernel Version:             5.4.0-1073-azure
  OS Image:                   Ubuntu 18.04.6 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.4.12+azure-3
  Kubelet Version:            v1.21.9
  Kube-Proxy Version:         v1.21.9
PodCIDR:                      10.244.4.0/24
PodCIDRs:                     10.244.4.0/24
ProviderID:                   azure:///subscriptions/9da7523a-cb61-4c3e-b1d4-afa5fc6d2da9/resourceGroups/mc_rg-pc-cng_cngcluster_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-users-14533555-vmss/virtualMachines/6
Non-terminated Pods:          (7 in total)
  Namespace                   Name                             CPU Requests  CPU Limits  Memory Requests   Memory Limits     AGE
  ---------                   ----                             ------------  ----------  ---------------   -------------     ---
  dhub                        continuous-image-puller-sjgbk    0 (0%)        0 (0%)      0 (0%)            0 (0%)            6m46s
  dhub                        jupyter-taugspurger              1650m (21%)   4 (51%)     7301444403 (25%)  8053063680 (27%)  2m21s
  dhub                        user-placeholder-0               1650m (21%)   4 (51%)     6800M (23%)       7500M (25%)       6m17s
  kube-system                 azure-ip-masq-agent-lw66b        100m (1%)     500m (6%)   50Mi (0%)         250Mi (0%)        6m56s
  kube-system                 csi-azuredisk-node-wzkmr         30m (0%)      0 (0%)      60Mi (0%)         400Mi (1%)        6m56s
  kube-system                 csi-azurefile-node-wzrqc         30m (0%)      0 (0%)      60Mi (0%)         500Mi (1%)        6m56s
  kube-system                 kube-proxy-tfdgv                 100m (1%)     0 (0%)      0 (0%)            0 (0%)            6m56s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests           Limits
  --------                       --------           ------
  cpu                            3560m (45%)        8500m (108%)
  memory                         14279702323 (49%)  16758926080 (57%)
  ephemeral-storage              0 (0%)             0 (0%)
  hugepages-1Gi                  0 (0%)             0 (0%)
  hugepages-2Mi                  0 (0%)             0 (0%)
  attachable-volumes-azure-disk  0                  0
Events:
  Type     Reason                   Age                    From        Message
  ----     ------                   ----                   ----        -------
  Normal   Starting                 6m56s                  kubelet     Starting kubelet.
  Warning  InvalidDiskCapacity      6m56s                  kubelet     invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  6m56s (x2 over 6m56s)  kubelet     Node aks-users-14533555-vmss000006 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    6m56s (x2 over 6m56s)  kubelet     Node aks-users-14533555-vmss000006 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     6m56s (x2 over 6m56s)  kubelet     Node aks-users-14533555-vmss000006 status is now: NodeHasSufficientPID
  Normal   NodeAllocatableEnforced  6m56s                  kubelet     Updated Node Allocatable limit across pods
  Normal   Starting                 6m50s                  kube-proxy  Starting kube-proxy.
  Normal   NodeReady                6m46s                  kubelet     Node aks-users-14533555-vmss000006 status is now: NodeReady
